name: CI build

# Controls when the action will run. 
on:
  workflow_dispatch:
    inputs:
      version: 
        description: "node-red base image"
        required: true
        default: "2.2.2"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: minor
          dry_run: true
      - name: Build and push
        uses: docker/build-push-action@v2.2.2
        with:
          context: build-context
          file: build-context/Dockerfile
          platforms: linux/arm/v7,linux/amd64
          build-args: |
            BASE_IMAGE=nodered/node-red:${{ github.event.inputs.version }}
          push: true
          tags: |
            wagoautomation/node-red-iot:${{ github.event.inputs.version }}-${{ steps.tag_version.outputs.new_tag }}
            wagoautomation/node-red-iot:${{ github.event.inputs.version }}
      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: minor
